### ISSUE TITLE
terraform for AWS fails to reliably provision

### ISSUE THREAD

**Issue by jmery** [habitat-sh/national-parks#30]
Many folks (me, @ericcalabretta, @galenemery, and others) routinely have `tf apply` fail when run for AWS.  A full log file is attached from my most recent attempt, but we can gather others as well.  Additionally, let me know if there are other logs I should gather.

[tf-aws.log](https://github.com/chef-cft/national-parks/files/2095389/tf-aws.log)

When using the terraform-native `habitat` provisioner, there are no issues.  It works every time.

CC / @echohack @smford22

**Comment by jmery** [comment]
i tracked it down to the `sudo hab svc load...` command in the shell script used by tf during provisioning.  what's happening, is that `svc load` command is running too quickly and things aren't totally started and running.  if you wait a bit, even 10 seconds, everything works super reliably.

i added a `sleep 10` to the tf plan for the mongo and parks peers.  thoughts on adding that in as a PR to national-parks?  or is there something else we need to troubleshoot to really get this squared away?

**Comment by echohack** [comment]
Hey @jmery ! Yes, please PR away.

The other thing we can do here is switch from Ubuntu to our high perf Centos VMs, which tends to bring up things quicker. I think combined, both of these should fix the issue.
